### ISSUE TITLE
Add url annotation?

### ISSUE THREAD

**Issue by bdarcus** [minad/marginalia#101]
Embark has a url category and `embark-url-map`. Not sure what it might include that's convenient, but perhaps it would make sense to add a basic accompanying annotation here?

**Comment by minad** [comment]
The embark url map is mostly useful for urls at point. Are there commands in Emacs which select from a list of urls via completing-read? What kind of annotation would you like to show with an URL, there is not really any contextual information we could show since all we've got is the url string itself.

**Comment by bdarcus** [comment]
> There is not really any contextual information we could show since all we've got is the url string itself.

Yeah, now that I think about it, it doesn't make sense here.

This only occured to me when experimenting with `consult--multi`, which adds an annotation if one isn't available, but it's not useful. So I guess if anything this should go on the consult tracker.

**Comment by minad** [comment]
Okay :+1:
