### ISSUE TITLE
Annotating projectile completing read

### ISSUE THREAD

**Issue by carlf** [minad/marginalia#110]
I saw the issue open on projectile about them not passing the appropriate metadata in their calls to completing read. In an attempt to work around the issue in the meantime, I have the following:

```
(use-package marginalia
  :straight t
  :after vertico
  :bind (("M-a" . marginalia-cycle))
  :init
  (setq marginalia-command-categories
        '((projectile-find-file . project-file)
          (projectile-find-dir . project-file)
          (projectile-switch-project . file)))
  (marginalia-mode))
```

This works as expected and I get appropriate annotations on the three commands listed in my setq. What I find, however, is that projectile will, by default, call `projectile-find-file` as soon as a project is selected. Somehow, despite by categories set as above, it seems to not pass through to this second call. Is there a way to get marginalia to annotate even if the command was not called directly?

**Comment by minad** [comment]
> I saw the issue open on projectile about them not passing the appropriate metadata in their calls to completing read. In an attempt to work around the issue in the meantime, I have the following:

This may work however you should note that `project-file` is the category used by `project.el` and not `projectile`! You may want to consider using `project.el` instead of `projectile.el` or define *projectile-specific categories* like `projectile-file`.

> This works as expected and I get appropriate annotations on the three commands listed in my setq. What I find, however, is that projectile will, by default, call projectile-find-file as soon as a project is selected. 

Which command does this? If you call `projectile-switch-project` it first asks for a project and then asks for a file? Maybe you are hitting the issue that the command reads *twice* from the minibuffer. Then `marginalia-command-categories` does not detect the command correctly. Only the first read from the minibuffer can be categorized using `maginalia-command-categories` for technical reasons, since Marginalia uses the value `this-command`. The value of `this-command` will be overwritten for the second read from the minibuffer.

**Comment by carlf** [comment]
Ok. So if I'm understanding correctly, project.el should work out of the box for this sort of thing? They seem to offer similar functionality so I'm not married to using projectile. It's just inertia at this point.

**Comment by minad** [comment]
Yes, as far as I can tell project.el works well ootb now. project.el saw a lot of great development recently - note that while project.el is built into Emacs, you can install the newest version separately. I am not sure if projectile/project.el are functionally equivalent, there may be some gaps. However from my experience project.el does everything I need (basic project detection and it has the most important project specific commands). Then I use commands like `consult-ripgrep` which provides a fast asynchronous project-wide search.
