### ISSUE TITLE
-annotate-binding and -char also propertize space and parens

### ISSUE THREAD

**Issue by ilohmar** [minad/marginalia#116]
Title basically says it all: this behavior becomes quite obviously unwanted if the face used has an underline or box (which will include the leading space and the wrapping parentheses).  Simple test: let `marginalia-key` face inherit from `help-key-bindings`, and check `amx` or a similar command.

The fix is to swap the format and the propertize calls, eg,
```elisp
(defun marginalia-annotate-binding (cand)
  "Annotate command CAND with keybinding."
  (when-let* ((sym (intern-soft cand))
              (key (and (commandp sym) (where-is-internal sym nil 'first-only))))
    (format " (%s)" (propertize (key-description key) 'face 'marginalia-key))))
```
, and likewise for `marginalia-annotate-char`.

Full disclosure: I would personally still want to override these functions to remove the "(" ")" chars, which are unnecessary when the annotation face stands out.  So if there are any ideas floating around for even more customizable annotations, that would surely be interesting.

**Comment by minad** [comment]
Thank you for the report. Indeed we can do a bit better by not propertising the space in front of the opening parenthesis. However the parentheses should still be highlighted. This is intentional. I improved the highlighting in https://github.com/minad/marginalia/commit/f945fa5c72907f0c96348956cbd9e84a3c6495c0.

> I would personally still want to override these functions to remove the "(" ")" chars, which are unnecessary when the annotation face stands out. So if there are any ideas floating around for even more customizable annotations, that would surely be interesting.

Yes, this is the only way to achieve a customization which fits your preferences. See #95 regarding possible customizations. So far I have not seen the need and nobody came forward with a reasonable proposal. If you are not happy with an annotator the best approach is to simply replace the annotator with your own function. You can still reuse some code but we don't have support for reusability/configurability on the sub-annotator level. In contrast, ivy-rich builds up the annotators one by one from a list. I am not fond of that approach honestly.

**Comment by ilohmar** [comment]
Got you, thanks for the reply.
