### ISSUE TITLE
jka-compr-insert-file-contents: Opening input file: error uncompressing 5x5.el.gz,

### ISSUE THREAD

**Issue by abcdw** [minad/marginalia#132]
With marginalia-mode enabled, on `find-library` I get the following error:

```
jka-compr-insert-file-contents: Opening input file: error uncompressing 5x5.el.gz, /gnu/store/9cjnp6d3qhx1gp5jk01isnna36p3b5jn-emacs-next-pgtk-latest-29.0.50-1.172c055/share/emacs/29.0.50/lisp/play/5x5.el.gz
```

It happens automatically with vertico and on TAB press, when using default completion buffer.

Happens on 097bd81743026c9b4889b860efd0283b26e64ccf and probably earlier versions too.

**Comment by minad** [comment]
Please attach the file which breaks here. I haven't seen uncompression errrors on my system.

**Comment by abcdw** [comment]
Thank you very much for the fix, it works for me.

Not sure if making marginalia depend on gzip and coreutils is a good idea in long-term, but it works. I'll report separately if I find it problematic.

**Comment by minad** [comment]
> Not sure if making marginalia depend on gzip and coreutils is a good idea in long-term, but it works. I'll report separately if I find it problematic.

Emacs itself uses these commands behind the scene in jka-compr, otherwise I wouldn't have gone that route. But it could be that we have to make the library command configurable in the long term or that we have to auto detect different compression programs. I doubt that the current approach works on Windows, but Windows doesn't have high priority for me since I also don't have convenient access to it.

**Comment by hmelman** [comment]
I found this change didn't work for me on macos, no library had their doc string included in the annotations.  The problem was the `zcat` command on macos failed as described [here](https://serverfault.com/questions/570024/zcat-gzcat-works-in-linux-not-on-osx-general-linux-osx-compatibility).  One of the answers there, using `zcat < %s` instead of `zcat -f %s` only partially worked (some doc strings appeared, not all).  What did work for me was installing the gnu gzip packages via homebrew, `brew install gzip`.  I don't think marginalia needs to change for this, but someone with this problem finding this bug can find an answer here.

**Comment by minad** [comment]
Is something else available ootb in Mac? For example `gunzip -c`?

**Comment by hmelman** [comment]
There is but it behaved the same as `zcat < %s`, only working for some libraries (assume the difference is those that are .el vs .el.gz but didn't check).  The problem is what's installed on macos is very old versions of gnu packages because they wouldn't go to gplv3.

**Comment by minad** [comment]
@hmelman please check https://github.com/minad/marginalia/commit/26f2bd9ee7b63bcad6604108e2f565b34bc6083b

**Comment by hmelman** [comment]
> @hmelman please check [26f2bd9](https://github.com/minad/marginalia/commit/26f2bd9ee7b63bcad6604108e2f565b34bc6083b)

It works. :)
