### ISSUE TITLE
Include in README some info about adding an affixation-function

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#138]
I wanted to try writing an affixation-function to use with unicode characters to render the character as a prefix˜ the way `counsel-unicode-char` does.  I wrote the function below as a first attempt (not sure it will work, comments welcome) but then I couldn't figure out how to tell marginalia to use it.  Do I just put it in `marginalia-annotation-registry`?  Do I have to add some metadata saying it's an affixation-function?  (I got that sense looking at `marginalia-cycle` but wasn't sure).  Some hints or an example in the README would help.

```elisp
(defun marginalia-affixation-char (cand)
  "Annotate character CAND with its general character category and character code."
  (when-let (char (char-from-name cand t))
    (list cand
	  (format #("(%c) " 1 5 (face marginalia-char)) char)
	  (marginalia--fields
	   ((format "%06X" char) :face 'marginalia-number)
	   ((char-code-property-description
             'general-category
             (get-char-code-property char 'general-category))
	    :width 30 :face 'marginalia-documentation)))))
```

**Comment by minad** [comment]
Marginalia doesn't support prefixes or the affixation-function. The affixation-function is only used internally to align the annotations. But I don't plan to add support for prefixes to the annotators specified in the marginalia-annotator-registry since this will only lead to an incoherent UI overall. You can of course modify the completion-metadata-get advice of Marginalia to support your use case.
