### ISSUE TITLE
Wrong margin text applied to symbols

### ISSUE THREAD

**Issue by andreyorst** [minad/marginalia#140]
Hi! I've notived that sometimes text, displayed next to a certain candidate doesn't make a lot of sense in the context:

![image](https://user-images.githubusercontent.com/19470159/166981198-4f041c6d-7f75-4437-a2e4-a58de5f2d5eb.png)

In the picture above, a `shadow` is a type of a ClojureScript REPL for a shadow-cljs projects. Marginalia displays a text of a face, named `shadow`, which is not a huge problem, just a small inconvenience.

It seems that this happens if the candidate is a symbol, and not a string, e.g.:

```emacs-lisp
(completing-read "foo" '(shadow default))
```

I don't know if this is a solvable issue, so feel free to close it if it's out of the scope of the project.

**Comment by minad** [comment]
This can happen. Marginalia uses heuristic classifiers to determine the completion category. In this case marginalia-classify-symbol gives a false positive. You can correct this on a case by case basis via marginalia-command-categories or marginalia-prompt-categories.

**Comment by minad** [comment]
However one can argue that it is not even a false positive since we are in fact completing symbols with

(completing-read "foo" '(shadow default))

(@oantolin as far as I know symbol lists are discouraged because of the potential overlap with lambda/closure consp. Should we instead (or additionally) check for symbol alists?)

**Comment by oantolin** [comment]
@andreyorst I think I agree with @minad: since people use completing-read without metadata, Marginalia resorts to heuristics and it is expected that it gets it wrong sometimes. The best thing to do is for users to fix cases as they arise, which Marginalia gives you the tools to do. For example, a quick `(add-to-list 'marginalia-prompt-categories '("ClojureScript REPL" . clojure-script-repl))` should fix it (I'd probably use `marginalia-comman-categories` for this case instead, but I don't know the name of the command you ran 😄). And not only does it fix it, it also opens the door for you to write an annotator if you want, maybe you'd like to annotate each type of REPL with the information of whether you have one of those already running; something liek that.

@minad:

> as far as I know symbol lists are discouraged because of the potential overlap with lambda/closure consp. Should we instead (or additionally) check for symbol alists?

We don't fall for the lambda/closure trap because we are checking for `(and (not (functionp mct)) (consp mct) (symbolp (car mct)))`.

We don't currently check for alists with symbol keys, maybe that's worth adding, but I think we probably would have noticed a use-case by now, so probably it's not important.

**Comment by andreyorst** [comment]
@oantolin, @minad thanks for thorough explanation!
