### ISSUE TITLE
Candidate width taking up too much space

### ISSUE THREAD

**Issue by justinbarclay** [minad/marginalia#145]
I'm sorry, I am not sure if this is meant to be in Marginalia or Vertico, but because this affects the UX of Marginalia, I am posting here first. 

When using consult-buffer, some of the recentf becomes _really_ long. So I try to truncate the candidate as shown below, but the length of the actual file name seems to affect the width of the column and not the length of the displayed file name. Is there a way to override the width of the candidate column?
![image](https://user-images.githubusercontent.com/6868388/182441106-2aa61078-c0f1-4816-8d46-2be44ed4ab17.png)

**Comment by minad** [comment]
This candidate truncation should be solved on the level of the UI. However the problem is that Marginalia also takes the candidate width into account for the alignment computation, so it could be that this will introduce more issues. See https://github.com/minad/vertico/issues/198 for a related discussion and a way on how to truncate in Vertico. I hope this helps in your use case. Please let me know if this works.

---


More generally I don't really see a good solution which will solve this issue in a clean and general way given the current annotation APIs. We are hitting the limitation of the affixation-function/annotation-function which is used by Marginalia under the hood. A possible way out would be a more general decoration-function which pushes formatting and alignment of columns completely to the UI. There has been discussion about such a more general api before on the emacs bug tracker and the vertico/consult/marginalia trackers, but nothing has materialized so far.

**Comment by minad** [comment]
Btw could you please post your relevant configuration and tweaks to Vertico/Marginalia/Consult for future reference? You could also add it to the Vertico wiki. This may be helpful for others as stop gap measure until we've found and implemented a better solution.

**Comment by minad** [comment]
Now I found the older discussion which summed up the situation regarding alignment annotation/truncation pretty well: https://github.com/minad/consult/issues/565. Unfortunately this leads into quite a rabbit hole...

**Comment by minad** [comment]
To take a step back - for your issue it should also be sufficient to set marginalia-align to center and set marginalia-align-offset to an appropriate value. Of course this has other downsides where the alignment may get messed up.

**Comment by justinbarclay** [comment]
Thanks for pointing this out, I did try that but ran into issues in that, I wanted a max-width string that was much shorter, and the alignment didn't work out too well.

It truncates the string, but the alignment is still off
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/6868388/182478959-71efbf8c-4629-4485-abf1-36123b8f6b3c.png">

I've bastardized things a little bit, so I am unsure if you like the UX, but I added an extension point in marginalia--align that allows the truncation of any candidate. (With some mechanism inspired from your highlight example).
```emacs-lisp
(use-package marginalia
  :config
  (setq marginalia-max-relative-age 0)
  (setq marginalia-align 'left)
  (defun +marginalia-category-truncate-files (cand)
    (if-let ((type (get-text-property 0 'multi-category cand))
             ((eq (car-safe type) 'file)))
        (truncate-candidate-to cand 30) ;; some string truncation function
      cand))
  (defun +marginalia-truncate-helper (cand)
    (if-let ((func (alist-get (vertico--metadata-get 'category)
                              +marginalia-truncation-func-overrides)))
        (funcall func cand)
      cand))
  (defvar +marginalia-truncation-func-overrides
    `((file . ,#'+marginalia-category-truncate-files)
      (multi-category . ,#'+marginalia-category-truncate-files))
    "Alist mapping category to truncate functions.")

  (defun marginalia--align (cands)
    "Align annotations of CANDS according to `marginalia-align'."
    (cl-loop for (cand . ann) in cands do
             (when-let (align (text-property-any 0 (length ann) 'marginalia--align t ann))
               (setq marginalia--candw-max
                     (max marginalia--candw-max
                          (+ (string-width (+marginalia-truncate-helper cand)) ;; we calculate truncated candidate's width here
                             (string-width (substring ann 0 align)))))))
    (setq marginalia--candw-max (* (ceiling marginalia--candw-max
                                            marginalia--candw-step)
                                   marginalia--candw-step))
    (cl-loop for (cand . ann) in cands collect
             (progn
               (when-let (align (text-property-any 0 (length ann) 'marginalia--align t ann))
                 (put-text-property
                  align (1+ align) 'display
                  `(space :align-to
                          ,(pcase-exhaustive marginalia-align
                             ('center `(+ center ,marginalia-align-offset))
                             ('left `(+ left ,(+ marginalia-align-offset marginalia--candw-max)))
                             ('right `(+ right ,(+ marginalia-align-offset 1
                                                   (- (string-width (substring ann 0 align))
                                                      (string-width ann)))))))
                  ann))
               (list (+marginalia-truncate-helper cand) "" ann)))) ;; We truncate candidate here.
  :bind
  (("M-A" . marginalia-cycle))
  :init
  (marginalia-mode)
    ```
    
    Which then ends up looking like.
    
<img width="996" alt="image" src="https://user-images.githubusercontent.com/6868388/182482139-9e4df53b-4bc8-447b-9eef-4d06bcf171ea.png">

**Comment by minad** [comment]
Thanks! The problem with your solution is that you truncate the candidate in the affixation-function. As far as I know, such a modification of the candidate is disallowed and will cause issues in certain completion UIs. It may work fine in your configuration bit it is not a solid solution which we can use here. It is a rabbit hole 🤷

**Comment by justinbarclay** [comment]
Yeah, I understand, and I appreciate my lack of knowledge in this area of Emacs. While trying to solve some of my problems, I started looking around at what Emacs had for completion system configuration, and as you said, it's a rabbit hole, so I tackled it at a more surface level. 🤷

**Comment by minad** [comment]
> trying to solve some of my problems

If your problems are only on this superficial level (alignment etc)  you are lucky. :)

To be clear, the Vertico/Marginalia/Embark ecosystem rather compromises on such kind of UI perfection in favor of sticking to the APIs we've got for the sake of better composability. I am quite happy with the Marginalia formatting even if it is not perfect.

**Comment by justinbarclay** [comment]
>> trying to solve some of my problems

> If your problems are only on this superficial level (alignment etc) you are lucky. :)
Very superficial and, yes, very lucky.

I hope it didn't come across as if I had any problems with Marginalia. I have no issues or concerns with the ecosystem you have built up. If what I wanted was impossible, I would have been more than happy with the defaults. This excursion was more the tinkerer in me, wondering what I would have to do to add back some of the aesthetic choices I was accustomed to. 

>  Vertico/Marginalia/Embark ecosystem rather compromises on such kind of UI perfection in favor of sticking to the APIs we've got for the sake of better composability

This is also why I decided to try and switch over from Ivy :)

**Comment by minad** [comment]
> I hope it didn't come across as if I had any problems with Marginalia. I have no issues or concerns with the ecosystem you have built up. If what I wanted was impossible, I would have been more than happy with the defaults.

No worries. While candidate truncation and improved formatting is certainly possible, for me there are two blockers to not proceed in the direction.

1. The APIs just don't naturally allow this and there is no general solution on how candidates should be truncated. As I argued the annotation formatting would benefit greatly from an improved API in contrast to the annotation-function and affixation-function. This needs some design work, discussions on emacs-devel and so on...
2. I consider the candidate always more important than the annotation (see also https://github.com/minad/consult/issues/565#issuecomment-1113985288), since you are matching against the full candidate. However there are some offenders like consult-recent-file or the recent file source of consult-buffer, where the candidate lengths get out of hand. You are not the first to complain about this issue.

> This excursion was more the tinkerer in me, wondering what I would have to do to add back some of the aesthetic choices I was accustomed to.

I wonder - do the other UIs like Helm or Ivy truncate the candidates?

**Comment by justinbarclay** [comment]
I agree, I think the primary issue is with recentf files being obnoxiously long as a default experience in emacs. 

With a basic config for `ivy` it defaults to only showing the file name for recentf files when switching buffers.
```
(setq recentf-save-file (concat user-emacs-directory ".recentf"))
(recentf-mode 1)
(setq recentf-max-menu-items 40)
(add-to-list 'load-path "~/.emacs.d/elpa/ivy-20220529.1130")
(require 'ivy)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(ivy-mode)
```
<img width="506" alt="image" src="https://user-images.githubusercontent.com/6868388/183143670-201dc487-ab4f-43aa-ba07-fe7ac1d3e935.png">

If I expand this to include ivy-rich, the equivalent of Marginalia, gets around this issue in three ways. One, it also leaves recentf files truncated to file name only. Two, it does not add any annotations to recentf files, so it doesn't have to align the columns related to buffers and recentf files. Three, if you dislike the default formatting of a candidate, it allows you to [customize](https://github.com/Yevgnen/ivy-rich#how-i-can-add-icons-for-ivy-switch-buffer)that as well. (I'm not suggesting these behaviours but merely documenting them). 
```
(add-to-list 'load-path "~/.emacs.d/elpa/ivy-rich-20210409.931")
(require 'ivy-rich)
(ivy-rich-mode)
(setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line)
```
<img width="505" alt="image" src="https://user-images.githubusercontent.com/6868388/183144420-afb81bb6-cf2e-4c96-94b9-5f28c1b1f624.png">

I can't help with helm as I've never used it.

**Comment by minad** [comment]
> I agree, I think the primary issue is with recentf files being obnoxiously long as a default experience in emacs.

For me the issue doesn't really occur since I usually have enough buffers open that I don't see the recent files immediately. Only then, the annotations will be pushed to the right. Another reason might be that my file hierarchies are rather shallow.

> With a basic config for ivy it defaults to only showing the file name for recentf files when switching buffers.

I see. We could implement this in Consult by changing the :items function of consult--source-recent-file (or you can do it in your user configuration - the sources are meant to be changed). For the consult--source-project-recent-file candidates we drop the project root from the file paths. The same approach could be used to drop the entire directory path. Alternatively the path could be hidden such that matching is still possible? But this may be more confusing. Does Ivy drop the path or does it hide the path only, such that matching is still possible?

> If I expand this to include ivy-rich, the equivalent of Marginalia, gets around this issue in three ways. One, it also leaves recentf files truncated to file name only. Two, it does not add any annotations to recentf files, so it doesn't have to align the columns related to buffers and recentf files. Three, if you dislike the default formatting of a candidate, it allows you to customize that as well.

You can also disable annotators in Marginalia via marginalia-cycle or by modifying the marginalia-annotator-registry. 

I am aware that Ivy supports candidate transformers and formatters. I consider transformers mostly a misfeature, but I must admit that I have them implemented in my user configuration. I added a +vertico-tranformer-function which is called by an advice of vertico--format-candidate and which is configured via vertico-multiform-mode. But so far I've only used this to add a face to directories in find-file.

As for the flexible ivy-rich column configuration, this is a nice feature. There has been some discussion about this before in #95, but so far this hasn't been requested often (or not at all?). Instead of using a column configuration, just write your own annotation function.

I had thought a while about a possible design for such a column configuration before. One possibility would involve the decomposition of each of the current annotation functions into one formatter function per column and an additional lookup function which either returns nil (invalid candidate, data not available) or some data which is then used by the column formatters. Then the annotator is put together by a configuration alist. Not sure if this is worth the effort. It sounds a bit over-engineered in comparison to the simple functions which we have now.

**Comment by justinbarclay** [comment]
> For me the issue doesn't really occur since I usually have enough buffers open that I don't see the recent files immediately. Only then, the annotations will be pushed to the right. Another reason might be that my file hierarchies are rather shallow.

Mine can be pretty deep, at work we have deeply nested folder structure for categorizing views and components in our web app.

For me, it's about having a consistent UI. For example when I scroll down and the columns jump drastically it becomes jarring for me. Being able to set fix or max width columns makes everything a lot more scannable/readable. However, I never thought to turn off the annotator for recentf in the switch buffers sections, so I think that might be a strategy I pursue.

> We could implement this in Consult by changing the :items function of consult--source-recent-file (or you can do it in your user configuration - the sources are meant to be changed)

Oh, neat, I think I skimmed over or didn't fully understand this the first time I was going through the docs, and this might get close to what I am looking for without shadowing internal functions.

> Does Ivy drop the path or does it hide the path only, such that matching is still possible?

Ivy drops the path entirely, which has the potential drawback of only allowing one copy of the same filename at a time in the recent candidates list. For example, if you had opened two README.md in two different projects, you'll only get the most recently opened README. This doesn't bother me, but it could be for some users 🤷.


> I added a +vertico-tranformer-function which is called by an advice of vertico--format-candidate and which is configured via vertico-multiform-mode. But so far I've only used this to add a face to directories in find-file.

Like you, I used this to separate files and directories but also to distinguish between active and inactive modes. I think the ability for candidates to have custom faces is a very nice feature. Using visual information to help distinguish candidates helps me narrow in on what I am looking for quickly. So, if I could suggest adding one feature to Vertico, it would be to support an official hook to change the face of a candidate based on some candidate property.

I know you have the wiki entry that talks about how to add faces to candidates but, as a user, advising functions feel like I am going against the author's intent and could break at any moment. Meanwhile, I like the idea of using an alist and mapping categories to a function that returns the name of a face to apply to the candidate could a nice user/library.

```emacs-lisp
(defun +completion-category-highlight-commands-face (cand)
      "Returns nil or the name of the face to apply to the current candidate."
      (let ((len (length cand)))
        (when (and (> len 0)
                   (with-current-buffer (nth 1 (buffer-list)) ; get buffer before minibuffer
                     (or (eq major-mode (intern cand)) ; check major mode
                         (seq-contains-p local-minor-modes (intern cand))))) ; check minor modes
          'highlight
      nil)
(add-to-list 'vertico-category-highlight '(command . ,#'+completion-category-highlight-commands-face))
```

>  Not sure if this is worth the effort. It sounds a bit over-engineered in comparison to the simple functions which we have now.

Myself, I am also quite happy with the simple function approach. Wrapping the annotator in `with--fields` allows me to treat almost everything as a column. So far, the only thing I've really wanted to change is the buffers annotation, everything else is beautiful 😊

**Comment by minad** [comment]
> For example, if you had opened two README.md in two different projects, you'll only get the most recently opened README. This doesn't bother me, but it could be for some users.

This would bother me, since I work on multiple projects with a similar structure.

> Like you, I used this to separate files and directories but also to distinguish between active and inactive modes.

Yes, I've seen that Ivy has that ability to distinguish modes with color. I don't understand why one would need that. I mean it looks nice but it does not seem to be worth the effort. I rarely toggle modes with M-x, I use a toggle map instead. Modes which I toggle rarely, quickly move down in the M-x history such that the coloring would be useless anyway. Furthermore only a small subset of all M-x commands are modes. I find it unjustified to color them specially. Anyway if coloring directories and modes is all that we come up with that is reason enough to not add this feature. 

I think I am more happy if Vertico presents the candidates as provided by the completion function itself and doesn't add its own modifications on top. For example Consult take a lot of care to format and highlight the candidates neatly. I am contradicting myself a bit here, since I use the aformentioned +vertico-transform-functions in my configuration for find-file. But my configuration also acts as a test-bed to see if a feature is worth being upstreamed.

> I know you have the wiki entry that talks about how to add faces to candidates but, as a user, advising functions feel like I am going against the author's intent and could break at any moment.

There is certainly a higher risk that something breaks, but Vertico is a simple package and you can easily adapt. I prefer to not stuff to many features into Vertico. Therefore some things are left to the wiki. If a feature proves useful enough it can still be added to Vertico itself. Ivy takes the opposite position, Ivy provides numerous configuration alists which seem to be used only rarely.

Note that the wiki advice you used isn't really optimal and overly complex. I suggest you use this instead, which is more unlikely to break:

~~~ elisp
(defvar +vertico-transform-functions nil)
(defun +vertico-transform (args)
  (dolist (fun (ensure-list +vertico-transform-functions) args)
    (setcar args (funcall fun (car args)))))
(advice-add #'vertico--format-candidate :filter-args #'+vertico-transform)
~~~

> So far, the only thing I've really wanted to change is the buffers annotation, everything else is beautiful

What exactly did you change there? Maybe we can change the Marginalia buffer annotator itself, if your proposal is reasonable enough such that most users would probably agree with it?
