### ISSUE TITLE
Items misaligned when completions-format is set to vertical

### ISSUE THREAD

**Issue by dr-scsi** [minad/marginalia#149]
Hi,

I'm observing misaligned items in the `*Completions*` buffer when `completions-format` is set to `vertical`.  To reproduce:

- Clone marginalia repo into `"~/lisp/marginalia"` (ce8db0acf7)
- emacs -Q (version 28.2 on Win10)
- In `*scratch*`, eval:  
```
(add-to-list 'load-path "~/lisp/marginalia" t)
(require 'marginalia)
(marginalia-mode 1)
```
- Now do <kbd>ESC-: (skip-TAB</kbd> which looks like this:  
![horizontal](https://user-images.githubusercontent.com/59777257/203751330-eeddbc2b-71eb-424b-8a40-15c96f0b839b.png)
- Now eval `(setq completions-format 'vertical)` and again <kbd>ESC-: (skip-TAB</kbd> which gives:  
![vertical](https://user-images.githubusercontent.com/59777257/203751786-51e977c3-57e5-4d42-9875-ddde1499daae.png)

Am I missing something?

**Comment by minad** [comment]
Marginalia works only well with completions-format one-column. Not sure if we could do better in the other cases. I welcome contributions or ideas but I don't want to special case any UIs.

**Comment by dr-scsi** [comment]
Thanks for your response.  To avoid misunderstandings: I don't want `marginalia` to do anything else than one-column, that's the way to go for it.  I think it should also work when a user has customized `completions-format` to something else than `one-column`; in my case it is `vertical`.  I want to have vertical sorting for completions where `marginalia` doesn't kick in.

Does this make sense?

**Comment by minad** [comment]
Yes, this means you have to somehow selectively enable/disable Marginalia and selectively modify completions-format per command or per completion category. For Marginalia you can disable the annotator per completion category (see marginalia-annotator-registry). You have to write some custom code if you want to change the completion settings per completion category (or per command). In Vertico I use vertico-multiform-mode for that.

Besides that one could imagine to add some code to Marginalia which detects if the UI is capable of displaying the annotations and otherwise bail out. But this would require that we add UI-specific code here, which is off the table.

**Comment by minad** [comment]
To take a step back and simplify a little bit: If you use vertical, disable the annotators, otherwise enable them. You could use a simple command like this to toggle:

~~~ elisp
(defvar completions-toggle--annotators marginalia-annotator-registry)

(defun completions-toggle ()
  (interactive)
  (if (eq completions-format 'vertical)
      (setq completions-format 'one-column
            marginalia-annotator-registry completions-toggle--annotators)
    (setq completions-format 'vertical
          marginalia-annotator-registry nil))
  (minibuffer-completion-help))
~~~

**Comment by dr-scsi** [comment]
Thanks, I will play with the suggestion above.  Reg. what you said:

> Besides that one could imagine to add some code to Marginalia which detects if the UI is capable of displaying the annotations and otherwise bail out. But this would require that we add UI-specific code here, which is off the table.

It is not viable to say: Marginalia doesn't care about the UI while doing its business, it temporary switches to `one-column` and restores whatever was in charge after exit?  Sorry for my ignorance, but I'm not familiar with the internals of Marginalia.

**Comment by minad** [comment]
> It is not viable to say: Marginalia doesn't care about the UI while doing its business, it temporary switches to one-column and restores whatever was in charge after exit?

Why should it? `completions-format` is a variable which is specific to the default completion UI. We don't add UI-specific code here. Also there is no place in Marginalia where this could be done. Marginalia is just a provider of annotation functions.

**Comment by dr-scsi** [comment]
Ok, got it.  So it is probably to Emacs itself to detect if completions are coming with annotations and switch to a more appropriate UI.  Thanks for the explanation 👍

**Comment by minad** [comment]
> Ok, got it. So it is probably to Emacs itself to detect if completions
> are coming with annotations and switch to a more appropriate UI. Thanks
> for the explanation 👍

Well, it is a complicated problem. The annotation-function is too weak,
since there is no way to distinguish between "long" and "short"
annotations. I've considered before to introduce a decoration-function,
which would resolve that and supplies more metadata. Then the UI could
decide if it wants the short or long annotations, and also the
formatting could be done more by the UI itself. The default completion
UI one-column layout would want the long annotation, the vertical and
horizontal format would want short annotations or no annotations at all.
Note that the column formatting is currently done by Marginalia, see
marginalia--fields.

**Comment by minad** [comment]
See also https://lists.gnu.org/archive/html/emacs-devel/2022-11/msg01569.html. The problem is not limited to Marginalia.

**Comment by dr-scsi** [comment]
Should be fixed now [with this change](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=6deeda411c0d2e25eab68ec4c2dccb626937e375).
