### ISSUE TITLE
Chained interactive calls and marginalia-command-categories

### ISSUE THREAD

**Issue by nbarrientos** [minad/marginalia#159]
Hi,

I've got this configuration:

```emacs-lisp
(add-to-list 'marginalia-command-categories
               '(project-switch-project . project))
```

Emacs' `project.el`'s [`project-switch-project`](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/project.el?h=9191fd50d242cde5256b876dd756ffbc6f46db90#n1820) allows to interactively select a project and then call interactively another command on it, for example `consult-project-extra-find`.

The issue is that with the configuration above, the items listed in the second chained interactive call (`consult-project-extra-find`) will also have the `project` category as `this-command`'s value is still `project-switch-project` when Marginalia processes the candidates of this second call.

It's arguable that this is a bug, I agree. I couldn't come up with a solution myself, but maybe you can think of something clever.

```
λ> emacs-version
"28.2"
λ> (pkg-info-package-version 'marginalia)
(20230411 444)
```

**Comment by minad** [comment]
Hi @nbarrientos,

this is a known issue affecting all commands which prompt twice or more times via the minibuffer. `project-switch-project` plus the chained command acts like a single command prompting twice. A possible fix could be implemented directly in `project-switch-project`. It could simply rebind `this-command` before calling the chained command. Besides that I have not come up with a good solution. 

~~~ elisp
(defun my-project-switch-project (dir)
  (interactive (list (project-prompt-project-dir)))
  (let ((this-command (project--switch-project-command))
        (project-current-directory-override dir))
      (call-interactively this-command)))
~~~

Ideally the minibuffer completion tables specify completion categories themselves or you use the `marginalia-prompt-categories` instead, such that the issue is avoided in the first place. Usually I consider the prompt classifier good enough, but I am happy to revisit this issue if we come up with a solution. 

See also https://github.com/minad/vertico/issues/332 for the related issue affecting `vertico-multiform-commands`. There one can also rely instead on categories via `vertico-multiform-categories`.

**Comment by nbarrientos** [comment]
Hi,

Thanks for the input. Actually, I'm stupid. `project.el` adds completion metadata so the choices in `project-switch-project` are already classified in category `project-file`. I'll build around that instead. :smile:

**Comment by minad** [comment]
> project.el adds completion metadata so the choices in project-switch-project are already classified in category project-file.

Right, I had forgotten about that!
