### ISSUE TITLE
Value annotations for Helpful

### ISSUE THREAD

**Issue by ashlineldridge** [minad/marginalia#160]
Hi,

This might be an issue with Helpful rather than Marginalia. When running `helpful-*` commands, I'd like to display Marginalia annotations that show the variable/function/etc values like you get by default with the standard `describe-*` commands. I suspect this might be because `helpful-*` completions are always assigned a completion category of `'symbol` whereas `describe-*` completion categories are correctly specified as `'variable`, `'function`, etc, which can then be looked up in `marginalia-annotator-registry`.

Marginalia annotating values for `describe-variable`:
<img width="724" alt="Screenshot 2023-05-11 at 1 04 42 pm" src="https://github.com/minad/marginalia/assets/363071/d6357132-1855-42cd-9555-cbd544647b04">

Marginalia not annotating values for `helpful-variable`:
<img width="568" alt="Screenshot 2023-05-11 at 1 18 25 pm" src="https://github.com/minad/marginalia/assets/363071/fa8a127a-3327-480d-805c-8de25fec5fb4">

As an aside, I've also noticed that when a `describe-*` value is truncated with ellipses, the description annotation is not aligned as shown in the first screenshot.

**Comment by hmelman** [comment]
FWIW, marginalia annotates `helpful-variable` just fine for me (just like it does `describe-variable`).  Emacs 28.2, macport.

**Comment by oantolin** [comment]
The way Marginalia detects that `describe-variable` candidates should be annotated as variables is through the command's prompt: the default value of the variable `marginalia-prompt-categories` includes an entry `("\\<variable\\>" . variable)`, which tells Marginalia that if a command's prompt matches the regexp `\<variable\>`, then the completion candidates for that command should be classified as variables.

Now, I notice that `helpful-variable`'s prompt is `Variable:`. Whether this matches `\<variable\>` or not then depends on whether the matching is case insensitive, i.e., on whether `case-fold-search` is true or false. So my conjecture is that @ashlineldridge sets `case-fold-search` to `nil` and @hmelman sets it to `t`.

I'll change the regexp in Marginalia's default configuration to `\<[Vv]ariable\>` to accommodate `helpful-variable` independently of `case-fold-search`. I don't use helpful myself, are there other commands for which we can make an analogous fix?

**Comment by oantolin** [comment]
After a quick test, I think `helpful-variable` is the only helpful command that doesn't get correctly annotated out of the box. Let me know if I missed anything.

**Comment by ashlineldridge** [comment]
@oantolin That's exactly what it is. Thank you @oantolin and @hmelman! Yes, you're right - it is just `helpful-variable` that was not showing the annotation.

**Comment by minad** [comment]
@oantolin I am not sure about the fix. From my experience adjusting `case-fold-search` in the user configuration is a dangerous change which has the potential to break many packages. `case-fold-search` is a fundamental design mistake in the Emacs APIs since it makes functions like `string-match-p` impure and depending on the context. We should either

1. not fix this and require the default value `case-fold-search=t`,
2. or let-bind `case-fold-search=nil` before `string-match-p` (but there are many places where we would have to do that across many packages)
3. or let-bind `case-fold-search=t` before `string-match-p` (but ...).

I tend to always assume `case-fold-search=t` and only let-bind it where I explicitly want to opt-out of case insensitive matching.

**Comment by minad** [comment]
I unfixed this issue for now. I usually don't do this. :) 

My problem with supporting `case-fold-search=nil` on the user configuration level is that this will open the door to many bug reports, which I am kind of unwilling to handle. This basically means that one has to wrap *every single* `string-match-p`, `string-match`, `replace-regexp-in-string` (and at least 10 functions more) with `(let ((case-fold-search t)) ...)` in order to make the behavior robust with respect to user configuration changes.

Therefore I would like to clarify this first. Is changing `case-fold-search` to `nil` a common pattern in user configurations? How many packages break due to this setting? Did you observe any other irregularities, @ashlineldridge? Do we really want to make the packages maintain robust against this change? Is the `(let ((case-fold-search t)) ...)` pattern common in Emacs packages and in the Emacs code base itself? Does it make sense to propose pure variants of the Emacs functions for addition to subr.el? Fortunately we could make them immediately available via compat.el, in the unlikely case that they make it through the emacs-devel discussion.

**Comment by minad** [comment]
@oantolin Yes, but this implies that `case-fold-search=nil` is a valid global setting. My current stance is that it is not. Therefore I am currently against this change or I want to see more convincing arguments first.

I was aware of the `case-fold-search`/`string-match-p` interaction for a long time and this means a lot of bugs at a lot of places. I am pretty sure that most packages are not robust if you set `case-fold-search=nil`.

**Comment by oantolin** [comment]
In other words, I don't view the situation as "Marginalia is only really meant to work under `case-fold-search = t` and it already supported helpful", I instead view it as "Marginalia patterns are as specific as possible, don't rely on the value of `case-fold-search` and we're written only to support built-in commands, but with a simple change will also support the popular third-party helpful package".

**Comment by minad** [comment]
Okay, I just grepped the Emacs code base and there are hundreds of `case-fold-search` let bindings. This is just horrible API design. This means we have to check all the uses of `string-match-p` and so on if they work fine for both values of `case-fold-search`. Maybe that's also a case for package-lint. It would have to check each use of these functions for local let-bindings.

**Comment by minad** [comment]
For now I pushed a fix which let-binds `case-fold-search=t` for the prompt classifier as @hmelman suggested in https://github.com/minad/marginalia/issues/160#issuecomment-1543965764 and `case-fold-search=nil` at a few other places. We can decide to change this to `case-fold-search=nil` but then we have to adjust most of the prompts I guess. It would be better to not match prompts like `bOoKmArK` but I've never seen such a thing. ;)

When I find time I will also take a look at some other packages if more adjustments are needed. For example I am pretty sure that Consult breaks at a few places with `case-fold-search=nil`.

**Comment by oantolin** [comment]
> As a test, I added a `case-fold-search=nil` binding to the prompt classifier and it broke multiple commands in my setup, also builtins.

I'm surprised, I thought "library" was the only case. For specificity, I'd still vote for writing the regexp to match under `case-fold-search = nil` and just fix them if built-in commands have different cases. But of course let-binding case-fold-search to t is fine too, and we can go with that.

**Comment by minad** [comment]
For example `customize-group` has the prompt `Customize group: ` and `read-color` has `Color: `, which were my mistakes. I am sure there are more cases. Then `consult-bookmark` has the prompt `Bookmark: `, but that's not a builtin. Again there are probably many more, if we take all the (M)ELPA packages into account.

**Comment by hmelman** [comment]
FWIW, I always viewed `marginalia-classify-by-prompt` as a useful hack until calls to `completing-read` were updated to set a category on their completion tables.  As such, a heuristic in it to set `case-fold-search` to `nil` seems fine to me and doesn't mean that everything else in "iceberg" has to support `case-fold-search` customized to `nil` particularly since this is the first time you've run across issues with it.

**Comment by minad** [comment]
> FWIW, I always viewed marginalia-classify-by-prompt as a useful hack until calls to completing-read were updated to set a category on their completion tables.

The problem is that completion categories are only useful for completion styles, Marginalia and Embark. This is not sufficient to convince everyone to add the categories. On top, specifying a completion category only is inconvenient since you have to construct a completion table manually (in contrast to `consult--read`).

> As such, a heuristic in it to set case-fold-search to nil seems fine to me and doesn't mean that everything else in "iceberg" has to support case-fold-search customized to nil particularly since this is the first time you've run across issues with it.

I added a few more let-bindings to my packages. You are probably right that the issue is not widespread, but I also suspect that not many users set case-fold-search to nil.

**Comment by oantolin** [comment]
I think I've changed my mind and now prefer this fix of let binding `case-fold-search` to `t` in `marginalia-classify-by-prompt`. I mean the only advantage of my proposal was "specificity", but I think "this word appears as a word in the prompt" is specific enough.

**Comment by oantolin** [comment]
> Okay, I just grepped the Emacs code base and there are hundreds of `case-fold-search` let bindings.

Mostly binding it to nil, I imagine?

**Comment by minad** [comment]
@oantolin No, actually more bindings to t.

**Comment by ashlineldridge** [comment]
> Therefore I would like to clarify this first. Is changing case-fold-search to nil a common pattern in user configurations? How many packages break due to this setting? Did you observe any other irregularities, @ashlineldridge?

I must admit, I wasn't aware of the issues around changing the default value of `case-fold-search`. Coming from other editors/IDEs, I was surprised by the default case-insensitive matching of Emacs, and so changed its value to `nil` early on in my Emacs journey. I hadn't noticed any negative side-effects by changing it - though perhaps certain packages were providing incorrect results without me noticing.

**Comment by minad** [comment]
@ashlineldridge If it works well for you that's great. Personally I am okay with the case insensitivity of Emacs and always considered changing this default too problematic so I never even tried it. But it probably works alright in most cases, as @hmelman mentioned. I pushed a few changes across my packages to make them robust for both values of case-fold-search.
