### ISSUE TITLE
Right align broken with describe-variable etc.

### ISSUE THREAD

**Issue by georgek** [minad/marginalia#164]
If I enable right align, like

```elisp
(use-package marginalia
  :bind (:map minibuffer-local-map
              ("M-A" . marginalia-cycle))
  :init
  (marginalia-mode)
  :config
  (setq marginalia-align 'right))
```

Then do `M-x describe-variable` (or `M-x helpful-variable`) etc. I get:

![20230829_22h04m39s_grim](https://github.com/minad/marginalia/assets/85981/ed880b03-4c11-4636-907c-a5b8a3052ab0)

**Comment by minad** [comment]
Sounds crazy, but this is the expected behavior if the window is not wide enough. The annotations are aligned at the right edge of the window minus the width of the annotation. The problem occurs if the width of the annotation plus the width of the candidate exceeds the window width. I recommend that you either set `marginalia-align` to `left` or `center`.

**Comment by minad** [comment]
I wonder why you want right alignment in the first place for such small frames. For small frames left alignment should work significantly better.

**Comment by georgek** [comment]
Left align looks weird with find file. It's a purely cosmetic thing, I just don't like the way it looks. If I could set different alignment per context then that would also work. But this works well enough.
