### ISSUE TITLE
display branch description when switching between them

### ISSUE THREAD

**Issue by zadca123** [minad/marginalia#176]
i was wondering if this feature is feasible
i add description of git branches, because branch names are mainly just ticket numbers in my case

**Comment by minad** [comment]
This is out of scope. Marginalia mainly targets built-in commands.

**Comment by hmelman** [comment]
It sounds like it could be useful for `vc-switch-branch` which is built-in.

**Comment by minad** [comment]
I see. I still don't consider "branches" an Emacs core concept, which we should annotate here. Such a branch annotator must not rely on git due to the vc abstraction, so this was maybe a little misleading above. However I am hesitant to add annotators here, which are too expensive, e.g., which require starting external processes.
