### ISSUE TITLE
consult-buffer does not work with marginalia

### ISSUE THREAD

**Issue by krdzo** [minad/marginalia#20]
Hi. I installed Marginalia to add annotations to Consul package but when I tried to run `consult-buffer` there were no annotations although when I run `switch-to-buffer` there are.
What I understand from the README is that the `marginalia-command-categories` variable is there to so that we can associate a command to a completion category so that the associated command gets annotations but there is no way to know what value is needed in `marginalia-command-categories`. 
From marginalia source code I saw that it needs an alist but I dont know what the KEY and VALUE pairs should look like. I tried something like 
```
(setq marginalia-command-categories
      '((consult-buffer . buffer)))
```
but it didn't work, so if can you add that explanation in the docstring of the variable so that we know how to set it.

**Comment by oantolin** [comment]
That is indeed the correct syntax, and it does in fact work for me. I tested with icomplete-vertical and with embark-live-occur. Are you using Selectrum?

**Comment by oantolin** [comment]
I just installed Selectrum to try it there and it didn't work. That's not too surprising: there is a separate implementation for Selectrum.

**Comment by oantolin** [comment]
I took a look at the selectrum implementation of consult-buffer and nothing that would cause this popped out at me. I'll let @minad handle this, he knows much more about Selectrum and wrote `consult-buffer`.

But anyway, I believe this is not a problem in Marginalia, and the docstring is presumably clear enough since you did correctly key and value. By the way, the reason `consult-buffer` doesn't automatically set the category as `buffer` is that it also includes bookmarks and recent files among the candidates.

**Comment by minad** [comment]
@krdzo consult-buffer does not support marginalia-annotations. In order to support this, we would need candidate transformers. This is well-known. But note that the marginalia annotations would not make much sense here since consult-buffer does not only present buffers, but also files, bookmarks and views.

**Comment by oantolin** [comment]
I just want to note that all my comments above were from before @minad merged the low-tech-consult-buffer branch into master. Now this setting you suggest, which previously did work with consult-buffer under icomplete-vertical (in the sense it annotated buffers, not other types of candidates), won't even work there now (because of an implementation detail: the candidates have prefixes to indicate their type).

**Comment by minad** [comment]
@oantolin Hmm, I have to rethink this. Multiple options:

* Implement candidate transformers (the design is unclear as of now)
* In consult, I can either introduce some default narrowing prefix, such that when narrowing to "b SPC" the candidates without prefix are shown.
* But what actually would make more sense is to simply introduce a category "virtual-buffer" and annotate appropriately for this special category. Right now I am annotating with "File", "Buffer", "Bookmark". See here https://github.com/minad/consult/commit/82c99168d0dc027da157ad7b32acb6d5b9caf541. I could use annotations instead which were more in line with what marginalia shows.

**Comment by oantolin** [comment]
I vote for `virtual-buffer`. The current File, Buffer, Bookmark could be the light annotator for `virtual-buffer` and and a heavy annotator could annotate each type as that type is usually annotated.

**Comment by minad** [comment]
@oantolin Yes but at this point it is not 100% clear how to proceed, I am not sure if I want to push these annotators to marginalia. Probably it makes more sense to have them in consult then for this special case, since the virtual buffer implementation by consult has these prefix implementation details. What do you think? Note that I am already using the annotation function in consult.

* Use a hardcoded annotator for consult-marginalia (this is what I am having now, but only the light variant)
* Move annotators marginalia, this violates the consult-marginalia boundary
* Keep annotators in consult and require the user to install the *special* annotator in marginialia for the virtual-buffer category (this is my favorite solution)

**Comment by oantolin** [comment]
You know, we could have our cake and eat it too: we can put the two annotators in consult, and hardcode one as the default. That way someone without Marginalia gets some annotation. But if a Marginalia user configure one or the other annotator, that takes precedence over the hardcoded default because we use `:before-until` advice in Marginalia.

**Comment by minad** [comment]
@oantolin I am not sure if this works - we don't overwrite the annotation function if one is present, right? This is the problem with the category-annotator separation. We overwrite categories per command, but we don't overwrite annotation functions as far as I know. We could also add an annotator function per command alist (going back to my original proposal ;)

But I think it would be still okay to provide two kinds of annotators in consult and the user could install them in consult. I could also auto-install them in consult, but this seems to be not-recommended in general for modern packages, see the discussion in https://github.com/minad/consult/pull/54

**Comment by minad** [comment]
The ugliness here is somehow that we cannot reuse the nice annotators from marginalia. If we would simply move the virtual-buffer annotators to marginalia, we could and simplifying things overall. But I am not sure if I want to add consult-specific annotators to marginalia.

**Comment by oantolin** [comment]
> I am not sure if this works - we don't overwrite the annotation function if one is present, right?

No, we do override them! Otherwise I'd never see docstring for commands, since Emacs annotates them with key bindings.

> I could also auto-install them in consult, but this seems to be not-recommended in general for modern packages

Yeah, let's not do that. One package shouldn't mess with another packages configuration.

> The ugliness here is somehow that we cannot reuse the nice annotators from marginalia.

Good point! Maybe just keep the current "Buffer, File, Bookmark" annotator in consult, but also report `virtual-buffer` as the metadatum in case someone wants to write a different annotator.

**Comment by minad** [comment]
I am a bit on the fence here. The over-engineered solution would be to create a marginalia-consult package. Alternatively we could just put the annotators to the marginalia package. It won't be much code and it won't really hurt anyone. If it turns out that there are many consult commands which need special annotators we couldl reconsider a marginalia-consult package or we have come up with an alternative solution by then. What do you think?

**Comment by oantolin** [comment]
You know what, I think doing what I said above, plus adding the heavy annotator to Marginalia is OK. Yes, it is consult specific, and needs to be aware of the prefix convention, but so what? It will never be used for people that don't use consult-buffer.

**Comment by minad** [comment]
Ok, I will push it here and we see how it goes. As long as we don't over do it, it will be okay and we can still move them out again. In general, we should try to avoid such boundary crossings.

**Comment by minad** [comment]
@oantolin I tested this and it actually works nicely from the technical pov. But the annotations do look so good because if I am annotating buffers and files, the annotations are obviously not aligned.

![ugly](https://user-images.githubusercontent.com/50754/101978372-a5b5b300-3c54-11eb-8837-646db65256fa.png)

**Comment by minad** [comment]
@oantolin I pushed it here https://github.com/minad/marginalia/commit/739469015cfccd3dba6a66aaaa3163a996b00f26
@krdzo Please test this and let us know if it works for you.

**Comment by oantolin** [comment]
So `consult` has no annotations in `consult-buffer` anymore? I was proposing something slightly different:

- Have a version of `marginalia-annotate-virtual-buffer-class` in `consult` (naming it `consult-annotate-virtual-buffer-class`, of course). This would be passed to `consult-read` as the `:annotate` parameter. This is feasible because that function doesn't need any Marginalia specific functions, and indeed you used to have it in consult, (as a lambda, I do suggest making it a named function). Doing this would mean that Consult users would get at least that basic annotation, even if they do not use Marginalia.

- Having only `marginalia-annotate-virtual-buffer-full` in Marginalia, and putting it in the heavy annotators alist. The `-full` function does belong in Marginalia since it uses other Marginalia annotators.

**Comment by minad** [comment]
@oantolin Yes that would be possible too. But I find it cleaner this way and it also avoids code reduction. There is no point in having annotations for some special commands in consult and no annotations for some other commands. If people want annotations they can use marginalia, this is what I will recommend :)

**Comment by oantolin** [comment]
Sure, fine by me.

I don't quite get what you mean by " it also avoids code reduction", though. I assume you meant "code repetition" (did you?). My proposal had no repetition, I proposed the light annotator in Consult, and the heavy one in Marginalia, with no repetion.

I'm happy with having both in Marginalia, of course, it feels more appropriate to have annotators in Marginalia.

**Comment by minad** [comment]
Sorry, yes. I avoid repeating marginalia--align etc in consult.

**Comment by oantolin** [comment]
Ah, got it, to avoid repeating `marginalia--align`, I hadn't considered that function. OK, I like your way better then.

By the way, I like this idea of allowing consult-specific annotations in marginalia. They are harmless to users of marginalia that don't use the consult functions the annotations are for. I think I might also add some consult-specific actions to embark, like that "save the line number on the kill ring" action I mentioned for the `line` category.

I already have a tiny thing about `line` in Embark: embark occur buffers for the `line` category use list view by default.

**Comment by krdzo** [comment]
> Are you using Selectrum?

Hi. Sorry that I'm late here and didn't answer any questions for the last 2 days, I was playing with github and somehow on accident disabled notifications for this issue. But yeah to answer you question I do use selectrum.

> @krdzo Please test this and let us know if it works for you.

And yeah I updated today and consult-buffer now works wonderfully. Thank you
