### ISSUE TITLE
Suggestion: docstring annotations should use font-lock-doc-face by default

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#22]
I get that `completions-annotations` makes sense, but I think `font-lock-doc-face` makes more sense for the first line of a docstring.  

It probably means you want `marginalia-file-name` face to default to something other than `marginalia-documentation`.  Personally I use `font-lock-variable-name-face` and `font-lock-type-face` for `marginalia-file-modes` face.

**Comment by minad** [comment]
I think completions-annotations makes actually more sense than font-lock-doc-face. But you can always tweak the settings or patch the theme you are using. I don't see a reason to change anything here.

**Comment by hmelman** [comment]
I won't protest, but can I ask why you think completions-annotation makes more sense?  My reasoning is that if I open the elisp file I'll see the same text in font-lock-doc-face, so seeing that same face used in marginalia is (a) consistent and (b) reinforces that that face is used for docstrings and (c) that this annotation is a docstring.  

I get that in general completions-annotation is made for all completion annotations, but you already use different ones for other kinds of annotations.  And I get that emacs has a very limited number of well defined faces for various semantic things.  But this case seems far more natural to me than choosing font-lock-keyword-face for maginalia-key and using that in several places or choosing font-lock-preprocessor-face for marginalia-file-owner.

**Comment by minad** [comment]
To be honest, I don't care too strongly. But it seems to me the completions-annotations face is specifically made for this purpose. If you have a symbol which only has a docstring, then this single annotation docstring will have the annotations face. I think that makes sense.

The font-lock faces are not used semantically here unfortunately. It would make more sense if Emacs defined a richer set of semantic faces by default. Then we could use those here. Since this is not the case we have to use some font-lock faces just to get something done - a good theme should overwrite those, e.g., the modus-themes.
