### ISSUE TITLE
Allow customization of column width.

### ISSUE THREAD

**Issue by JHonaker** [minad/marginalia#27]
As you recommended on the Reddit post, I'm opening this issue on GH.

As it currently stands, the marginalia leaves a ton of negative space when the frame is maximized. This is distracting when the number of columns is rather low. It would be easier to read if they were spaced closer.

The current behavior is to align the command/file/completion item to the left, and all other columns are aligned on the right.

I'd like to propose a modification/customization option to left align the columns, and add a fixed-width property to the completion item column.  This would allow for a viewing experience that is consistent with the visual presentation of tabular data in most programs.

**Comment by minad** [comment]
Using a constant candidate column width is too simple. This does not work well given that the widths of different candidates vary greatly. Furthermore the way Emacs implements annotations does not allow to scale the candidate column size. 

Alternatively we could add a whitespace column to the right which scales with large window sizes.

We should also keep the affixation function in mind since that allows us to get access to more information since we can obtain the column sizes of all visible candidates at once. But it might not be a good idea to use that information since that can result in rescaling every time you press a key during narrowing. This is clearly undesired.

**Comment by oantolin** [comment]
Marginalia doesn't do any formatting on completion candidates, only on annotations. A fixed-width column for completion candidates would have to be implemented by whatever package is actually displaying your completion candidates and annotations: Selectrum, Icomplete-vertical, the built-in `*Completions*` buffer, Embark's occur buffers, etc. (I don't actually know what you use to see the Marginalia annotations!) We can't do anything about that in Marginalia.

I think a fixed-width blank column at the right margin for large windows, as @minad suggested, is the way to go here. And I for one, would probably use that option.

**Comment by minad** [comment]
@oantolin I would make it fixed with but with some additional automatic shrinking on top as we are doing for the truncate-width and the separator.

**Comment by oantolin** [comment]
@minad Right, sorry, that's what I should have said. When I said "fixed-width", I only meant it would be a rectangle, that is annotations would stay right-aligned.

I think below a certain window width the blank column should be width 0, we only need for pretty large frames.

**Comment by JHonaker** [comment]
I use Selectrum, and I was about to recommend exactly the solution that's been arrived at before more carefully reading all of the comments.

I think the solution you've arrived at is perfect. Fixed width, relative to window size, blank column on the right hand side would solve the issue regardless of completion framework.

**Comment by minad** [comment]
@JHonaker Does it work for you with https://github.com/minad/marginalia/commit/531fb6e9a5070b9a94f80f19f7b0329c8b243d47?

**Comment by JHonaker** [comment]
Yea, that's much better.
