### ISSUE TITLE
marginalia--full-candidate broken due to marginalia--context

### ISSUE THREAD

**Issue by minad** [minad/marginalia#36]
Putting it here, such that we do not forget it.
See https://github.com/minad/marginalia/commit/cf9f411fe71ce2aa0b23fc758bdd002435142885.
 cc/@oantolin

**Comment by oantolin** [comment]
I fixed the problem that led to this issue on the Embark side, without any change to Marginalia. Now Embark runs annotators in the target window (which corresponds to what Marginalia does now), but temporarily sets the default-directory to that of the Embark occur buffer (since that one reflects the path in the minibuffer when the Embark occur buffer was created).

The `marginalia--full-candidate` function is fine, with its switching to an active minibuffer if there is one, and otherwise giving up and returning the candidate unchanged.

**Comment by minad** [comment]
Great!
