### ISSUE TITLE
nice concept

### ISSUE THREAD

**Issue by sjLambda** [minad/marginalia#37]
Like how well marginalia is integrated nonintrusively. Nice concept, however I had to disable for now due to speed and responsiveness. C-h f and C-h v are too slow for my use case. The slowness is probably due to the way marginalia reconstructs the doc strings. Perhaps I'm overlooking a caching mechanism or a simple workaround. I'm using marginalia with consult, selectrum, and ctrlf on the latest emacs trunk.

**Comment by minad** [comment]
@sjLambda Is this a bug report? If yes, we need more details.

In my setup Marginalia is not slow. I am using Selectrum/Icomplete-vertical on 27.1. Are you sure that you are using the newest version of Selectrum and Icomplete, since older versions did not apply annotations lazily?

We took some care to speed it up and perform caching for keybindings for example. Doc strings have a certain cost, that's right - since the docstrings are generated every time. There is not much we can do about this, except caching. I already optimized the truncation function such that we do not perform additional unnecessary allocations. But I don't see the need to perform caching.

Could you please describe a bit better when do you feel it is slow? Are you using this without Selectrum/Icomplete and TAB completion gets slow? There is not much we can do about that since *all entries* are annotated at once.

**Comment by sjLambda** [comment]
I am still stuck at the slowness after C-h a. I wasn't going to do this but since you asked, I did a simple profile-start and profile-report to notice that most of the time is being spent inside this function:

`(defun marginalia--function-doc (sym)
  "Documentation string of function SYM."
  (when-let (str (ignore-errors (documentation sym)))
    (save-match-data
      (if (string-match marginalia--advice-regexp str)
          (substring str (match-end 0))
        str))))`

I'm guessing substring is where the delay is. Since it's a copy operation of the entire text properties, it's a very expensive function for a dynamic list of 50K apropos items. It takes over 10 seconds (for C-h a) and 30 seconds (for C-h v) for the list to populate. Without marginalia they're almost immediate. 

I haven't tried this but see if copy without text properties might speed up; there used to be an alternate substring function that dropped all text-properties before copying. Perhaps that's where the speed up can mitigate the delay. Or look at revising that function without a substring copy at all.

**Comment by minad** [comment]
Ok, this sounds as if you are using an outdated selectrum/icomplete-vertical version. In the version I am using 10 items are annotated at once. Not 50000. This has definitely been fixed. If there is another side effect causing this, we have to recheck.

Can you test with emacs -Q and only loading **the newest** selectrum and marginalia version. Can you paste the git commit hashes of the versions you are using?

**Comment by sjLambda** [comment]
A manual update fixed it. I was using the melpa version of Oct 22, not the latest sources. Thanks.
