### ISSUE TITLE
`package-alist` is void, which causes errors

### ISSUE THREAD

**Issue by okamsn** [minad/marginalia#41]
I think this is because I use Straight.el instead of Package.el, so I think `package-alist` is never given a value.

I run into this error when trying to use `M-x straight-pull-package-and-deps`.

**Comment by iyefrat** [comment]
I am now running into this problem on the opposite end: since Doom only installs packages through straight, I don't get package annotations unless I have some package installed through `package.el` (this is not really supported by doom, but sometimes they stay around due to `emacs -Q` testing). When reverting 3c80428 I didn't run into the `package-alist` error, and I'm having trouble understanding how one would, since the `defvar` should circumvent that by setting it to `nil`, no?

**Comment by iyefrat** [comment]
Huh, that's a good point, the metadata doesn't necessarily correspond, especially with Doom specific overrides. I could probably extract the relevant general points into a `marginalia-straight` package as well. Thanks!

**Comment by minad** [comment]
Yes exactly. Note that you make the same "mistake" with the project-file annotator, since Doom does not use project.el but it's own project detection. Therefore you would also need your own annotator there if one wants to be strictly correct.

**Comment by minad** [comment]
I think I should elaborate a bit more. Ideally one should avoid both marginalia-* and embark-* packages, in this case marginalia-straight, embark-straight.

1. Instead of creating a marginalia-* package, contribute the annotators directly to the package. This way you don't necessarily depend on Marginalia. Furthermore specify a completion category in the completing-read calls, such that Embark can be used. A marginalia-* package may still make sense in rare cases if for some reason you cannot modify the original package, in this case straight.
2. Instead of creating embark-straight, contribute the action keymap as a prefix keymap directly to the original package. The user can then register this keymap in their configuration with Embark. Alternatively register the keymap in a `with-eval-after-load 'embark` block in the original package. This is the approach which is used for example by [Dtache](https://gitlab.com/niklaseklund/dtache). There is also some discussion on the Dtache issue tracker about the [integration](https://gitlab.com/niklaseklund/dtache/-/issues/2).

**Comment by iyefrat** [comment]
Of course depending on marginalia isn't ideal, but i think there is a significant drawback in writing your own annotation functions from scratch: loss of the marginalia formatting, truncation, and alignment facilities. This doesn't matter for small annotations, but in cases like packages where they are likely to fill the whole width of the minibuffer I'm not sure the tradeoff is worth it. I know that your intention is to not have marginalia be an annotation library, but I'm not really sure on why. I get the feeling that any sufficiently complicated annotation function will contain an ad hoc, informally-specified, bug-ridden, slow implementation of half of marginalia ;). There does seem to be a PR for straight annotations that seems to have stalled, I'll look into it.

**Comment by minad** [comment]
> there is a significant drawback in writing your own annotation functions from scratch: loss of the marginalia formatting, truncation, and alignment facilities.

I agree with that. If you want to use the formatting, a marginalia-* package is advised. In particular since the Marginalia formatting got better and richer, there is actual value there now. But...see below.

> I know that your intention is to not have marginalia be an annotation library, but I'm not really sure on why.

One could consider "librarifying" Marginalia like the Consult APIs. However I haven't been interested in library development so far. I think that such libraries which tweak some Emacs core facilities will ultimately become obsolete. Libraries and APIs should be offered by the Emacs core itself. In contrast, ideally the Emacs core should not add new packages, which are not libraries. Do you see what I mean? Emacs core is only for libraries, the ecosystem is only for functionality. Every ecosystem-level library will only lead to an ecosystem split. In contrast, every feature package which is adopted into the core will alienate parts of the community, which develops one of the competing packages. Generally I think Emacs development should be more decentralized with decentralized responsibilities, this means not controlling and not adopting feature level packages into core, keeping the responsibilities with the community. Needless to say that the Emacs maintainers have their own opinion which differs.

Of course these ideas and criteria are not applicable in all cases. For certain libraries it makes sense to develop them as part of the ecosystem, think an algorithm package, a special data structure package, e.g., for graphs, data format libraries, parser libraries etc. Things with some significant technical sophistication inside. The libraries we are talking about here, are nothing but thin layers on top of existing facilities and as such do not meet the technical threshold of a library.

**Comment by minad** [comment]
To conclude my argument - by writing feature/UI-level libraries I am directly helping the community with tools and make Emacs more accessible, and of course I also like to use these tools myself. If these tools become obsolete (let's say Vertico, Consult etc) there is not much damage done to the ecosystem, we will not end up with an unmaintained library package which is still strongly connected to large parts of the package ecosystem. For all these reasons my interests were more about writing such frontend tools and not so much with sophisticated backend libraries, which nobody is going to adopt anyways.
