### ISSUE TITLE
M-x apropos-value

### ISSUE THREAD

**Issue by sjLambda** [minad/marginalia#47]
I was torn between posting this feature request here and or in selectrum. But I thought I'd start here since it's related to C-h v enhancement.

M-x apropos-value is the flip side of searching for variables. Instead it searches the values contained in the variables. This is immensely useful to debug errors and for system-wide edits of paths, etc. 

Another way to look at it would be to re-arrange the extended columns of C-h v in marginalia and narrow the selection based on value. 

Is this something feasible within marginalia/selectrum or is it outside the scope?

**Comment by minad** [comment]
Thank you for the proposal! I think you are proposing a consult-apropos-value command. Some similar proposals have been discussed in the Consult wishlist, see https://github.com/minad/consult/issues/135.

This command does not sound feasible for minibuffer completion since generating the full string representation of all values is very costly. You can use describe-variable with marginalia and embark-collect-snapshot to get a full buffer you can search in. There it will show the marginalia annotations too, and in contrast to the minibuffer you can also search through them there. Try for example `isearch`, `consult-line`, `keep-lines` or `flush-lines`. However note that the values are truncated so you don't get the full string representation. But you can configure the truncation length in Marginalia if that is desired! I just tried this and it takes about 10s to run embark-collect-snapshot for describe-variable without any filtering. In the end you get the buffer, which is fully searchable.

Does this help you?

**Comment by oantolin** [comment]
> You can use describe-variable with marginalia and embark-collect-snapshot to get a full buffer you can search in.

Or use the built-in `*Completions*` buffer instead of embark-collect-snapshot.

**Comment by minad** [comment]
@sjLambda I close this. I hope this helps you!
