### ISSUE TITLE
Melpa

### ISSUE THREAD

**Issue by minad** [minad/marginalia#5]
@oantolin Are you ok with putting this on melpa? I prefer to add packages earlier than later in order to make it available to more users, gain feedback etc. Given that the functionality has been extracted from embark/consult I think it also makes sense in that case. Consult is already proposed for inclusion on melpa. What is holding you back from embarking into melpa btw?

**Comment by oantolin** [comment]
> What is holding you back from embarking into melpa btw?

Just laziness. I'll get on it now that I'm "back on GitHub", thanks to your energy.

**Comment by minad** [comment]
See https://github.com/melpa/melpa/pull/7274

**Comment by oantolin** [comment]
Well, actually I should update embark due to marginalia's existence. For one thing, I think maybe that just means stripping `:align-to` from the annotations (embark uses a tabulated list, and having the `:align-to` looks weird), possibly no other change.

If I want to do it without loss of functionality, I think I should make marginalia a dependence of embark. I don't want to make people install marginalia if it can't be done automatically, so this is my plan:

- Update embark for marginalia, but keep current classifiers and annotators, and current default configuration.
- Update the readme explaining how to configure embark to use marginalia right now.
- Submit to Melpa.
- Once both embark and marginalia are both on Melpa, make marginalia a dependency, update the default configuration of embark to use marginalia and remove the classifiers and annotators from embark.

Does that sound like a reasonable plan?

**Comment by minad** [comment]
> Well, actually I should update embark due to marginalia's existence. I think for now maybe that just means stripping :align-to from the annotations (embark uses a tabulated list, and having the :align-to looks weird), possibly no other change.

This was something I was worried about. I hope you can make the annotators work such that they look nicely in Embark!

> If I want to do it without loss of functionality, I think I should make marginalia a dependence of embark. I don't want to make people install marginalia if it can't be done automatically...

If you can make it without the dependency I would probably prefer that (Given that you probably don't have to call marginalia functions?). Maybe with some kind of soft dependency? But a dependency is okay too I guess. I am not sure how widely Embark is already used - it is still young. Maybe the current users could live with the breakage? In particular since it is not yet on Melpa and the current users installed the package more manually or via some other package manager like straight.

> Update embark for marginalia, but keep current classifiers and annotators, and current default configuration.

It all depends on if you want to break stuff for your current users, I guess. I would probably just cut out the stuff from Embark which can be replaced by Marginalia, introduce breakage and be done with it. The users can easily install Marginalia too. You can redirect any angry users towards me, since I proposed that ;)

**Comment by minad** [comment]
One thing I should add maybe - it also depends on how well marginalia works in the end as a replacement for the functionality you have right now in Embark. If it works perfectly, then things are good! The annotators look slightly different okay, but that's all?In Consult I simply removed consult-annotate-mode, since marginalia replaces it perfectly, but Consult is also younger.
