### ISSUE TITLE
marginalia display information about Guix package.

### ISSUE THREAD

**Issue by TxGVNN** [minad/marginalia#54]
Hi @minad. Thank for great package.

I'm using `guix` (https://gitlab.com/emacs-guix/emacs-guix) to manage my Guix package.
That is funny, marginalia display about Guix package base on emacs package.

`M-x guix-packages-by-name`                                                                          

![Screenshot from 2021-01-26 11-30-02](https://user-images.githubusercontent.com/9713793/105800692-40611b80-5f8f-11eb-9dfe-2449b9196f52.png)

**Comment by oantolin** [comment]
It's because the prompt contains the word "Package", so Marginalia assumes they are Emacs packages.

**Comment by TxGVNN** [comment]
> It's because the prompt contains the word "Package", so Marginalia assumes they are Emacs packages.

I think some packages in emacs use the word "Package" to manage their package in their system. So if we don't have solution for this, it look is not useful and lack of professionalism.

I even see it affect the actions of  `embark`, when it try to install `guix package` into Emacs system.

**Comment by oantolin** [comment]
It's easy to configure Marginalia to not annotate those, just do:

```elisp
(add-to-list 'marginalia-command-categories '(guix-package-by-name . guix-package))
```

**Comment by minad** [comment]
It seems to me that this issue can be closed.

> So if we don't have solution for this, it look is not useful and lack of professionalism.

@TxGVNN You are welcome to post issues here and we appreciate it. But please use an appropriate non-judgemental and professional tone.

@oantolin I wonder why Marginalia adds annotators to guix packages if guix already reports the guix-package-by-name category? Is this intensional? I know that we overwrite annotators. But in the classifier list, the original category comes before prompt etc.

**Comment by TxGVNN** [comment]
> You are welcome to post issues here and we appreciate it. But please use an appropriate, non-judgemental and professional tone.

Oh, Sorry for my ignorance. I don't know that is not good tone because english is not my native language and I'm a lazy guy to learn it correctly. I'm so sorry.

I just want to say the package is affect to another package, it seems a not good IMO. Sorry for my bad wording again.

**Comment by minad** [comment]
No worries. I just prefer a more friendly tone around. And I have often seen some kind of grumpiness in open source projects. After rereading my own comments I think I have been guilty of that too. But since it is written ambiguous language and since many of us are not native speakers, I think it is even more important to take a bit of care.

> I just want to say the package is affect to another package, it seems a not good IMO. Sorry for my bad wording again.

Sure, if there is a bug, it should be fixed. The issue you are mentioning is a bit of a pain point. I admit that and I have also been originally critical on doing too much auto-detection, which could be harmful. The problem is that the builtin commands often do not specify a completion category. We have to fix this here. The same applies to your guix commands. They do not specify a completion category.

In practice detecting the completion category based on the prompt string seems to work very well and I have not observed false classifications in my workflow. However I am also not using guix.

In general there are these possibilities to fix such issues:

1. Ensure that commands specify completion categories themselves. This is for example what I am doing in Consult. Every command specifies its category. (However I cannot just go to the Emacs source and modify every single command adding a completion category. I would have a hard time to get such a PR merged and it would be a huge waste of time.)
2. Refine the regular expressions used in the prompt classifier in Marginalia. 
3. Overwrite the completion category per command as @oantolin suggested above by adding to `marginalia-command-categories`.
4. Remove the problematic package prompt classifier from Marginalia and replace it by individual `marginalia-command-categories`. This is something you can do in your config too.

Since Marginalia allows this fine-grained configuration I am more or less satisfied by the status quo. It works well with Emacs out of the box. Users with special needs, e.g., Guix users like you, can adjust their configuration to circumvent any problems with false classification.

**Comment by TxGVNN** [comment]
> No worries. I just prefer a more friendly tone around. And I have often seen some kind of grumpiness in open source projects. After rereading my own comments I think I have been guilty of that too. But since it is written ambiguous language and since many of us are not native speakers, I think it is even more important to take a bit of care.

Thank you for your understanding. I will take a bit of care

About the issue, I don't understand so much. But IMO, I love to apply `marginalia` and `embark` base on each command instead of `completion categories`.
