### ISSUE TITLE
Better truncation method for file names

### ISSUE THREAD

**Issue by minad** [minad/marginalia#70]
Something like `../a/b/name`, `../a/dir/name` or `~/.../a/name`?

Affects `marginalia-annotate-buffer` and `marginalia-annotate-bookmark`.

**Comment by galeo** [comment]
Or you can consider providing custom settings, just like [`PROMPT_DIRTRIM`](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-PROMPT_005fDIRTRIM) provided by bash.

**Comment by robbert-vdh** [comment]
(whoops, I searched for an existing issue but using the wrong keywords I guess, summarizing my comment from #99)

Different options for this would be ideal! (and you could then of course still use your own truncation function if you really want something different) I recently started using the Vertico stack, and I ran into this today with `consult-buffer` where it basically becomes impossible to distinguish between similarly named buffers because the important bits of the path are cut off (see the screenshot below). Perhaps having an option that does something similar to `ivy-rich`'s behavior where it truncates the project's root would be nice. And I guess it would then also be possible to either do that only for files within the current buffer's project, or for any file in a project  I think `ivy-rich` also only showed the directory and didn't repeat the file name (because presumably the buffer's name reflects the file's name), but I guess that's mostly a stylistic choice so that's your call.

![screenshot](https://user-images.githubusercontent.com/748520/128601576-9cf48097-2e2f-4e81-a59f-5b9e4c159d73.png)

As a temporary workaround I've just [advised](https://github.com/robbert-vdh/dotfiles/blob/master/user/emacs/.config/doom/config.org#vertico) the function in my own dotfiles to strip the current project's root (without affecting files that are in a different project), and to abbreviate long paths outside of the current project. This ended up looking like this:

![afbeelding](https://user-images.githubusercontent.com/748520/128603358-12fed975-1514-45bd-9a14-1cc16c739864.png)

**Comment by minad** [comment]
@robbert-vdh The `shrink-path-file` function you are using comes from the `shrink-path` package? Unfortunately using this function is not an option for Marginalia which does not have any external dependencies. But we should replicate some similar path truncation method here. Removing the project root entirely is questionable imho as long as we don't print the project separately.

**Comment by robbert-vdh** [comment]
I think so, yes. I just checked what other things were using so I could hack something together with as little effort as possible :grin:. It's also not ideal for this, because it will for instance always make relative paths absolute, so it will even replace an empty string with an abbreviated version of `default-directory`. And I do agree that removing project roots unconditionally may not be a good idea. In my hacky workaround I just only did it only for the current project so there's no room for confusion there.

**Comment by minad** [comment]
We could print project paths as **project**/path/to/file. Anyways a PR implementing this feature is welcome.

**Comment by hikmet517** [comment]
I'm using this code that I wrote. [truncate-path.el](https://gist.github.com/hikmet517/e0e247d2a9db81d671c75d6e43619e75) Basically it's the 3rd option in op's comment.

In my init, I fset 'marginalia--truncate':
```
(load (expand-file-name "truncate-path.el" user-emacs-directory))
(fset 'marginalia--truncate 'truncate-for-marginalia)
```
Feel free to use it, test it, review it.

**Comment by jdtsmith** [comment]
Even simply left-truncating the file name would be a better solution.  Rarely is the earliest part of the filepath the most meaningful!

**Comment by minad** [comment]
@jdtsmith Good idea. I like it, obvious and simple. I am still open to using an improved truncation method in the future, but it is probably less relevant now.
