### ISSUE TITLE
Wrong information when a symbol has different meanings

### ISSUE THREAD

**Issue by DamienCassou** [minad/marginalia#72]
Here is marginalia showing imenu entries in the `marginalia.el` file:

![2021-04-25-081721](https://user-images.githubusercontent.com/217543/115982955-d0b6f880-a59e-11eb-8f25-2eef03827f52.png)

As you can see, I selected the `marginalia-mode` face in the minibuffer.

- Expected: The face's description is displayed by marginalia (e.g., "Face used to highlight...")
- Actual: The unrelated `marginalia-mode` command description is displayed instead (e.g., "Annotate completion candidates...")

**Comment by minad** [comment]
Currently we use the simple symbol annotator for imenu entries. We could implement a workaround which attaches type information to the imenu items and then uses the appropriate annotator (for example in this case the face annotator). In fact consult-imenu already attaches the necessary information (marginalia-mode is categorized under "Types" here), however this information is already lossy ("Types" instead of "Faces"). Alternatively we could use the line number information and based on that determine the correct type.

I think it is better to keep it as is and avoid workarounds here. Note that the annotator indicates the overloading of the symbol "marginalia-mode", it shows "cua", which means command, cUstomizable, fAce.
