### ISSUE TITLE
Splitting marginalia

### ISSUE THREAD

**Issue by DamienCassou** [minad/marginalia#74]
Hi,

marginalia is an awesome package, thank you. Good job!

Reading its code made me realize that it feels like 2 separate packages: one to classify and one to annotate classified candidates. Other packages (such as Embark) really may need the first one but not necessarily the second one. I think the code would be easier to understand if these 2 concerns where split into 2 files.

The two packages could be in the same repositories or in two different ones, it doesn't matter.

**Comment by minad** [comment]
Yes, we considered this before. I was the one particular in favor of creating two packages. @oantolin even proposed the two names Linnaeus for the classifer and Marginalia for the Marginalia. However it turned out that the classifier part is tiny in comparison to the rest. We would need a dependency from Marginalia to Linnaeus. Note that Embark also has a de-facto Linnaeus dependency in order to provide its actions. Originally Marginalia has been part of both Embark/Consult before and we extracted it for better reuse. This was a very good move. But another split here would be neither beneficial for the user nor for the developers.

**Comment by hmelman** [comment]
Now that you're getting patches into emacs, I'm hoping the classifier stuff in marginalia could be reduced and perhaps get marginalia back down below 500 lines once emacs 28 is the minimum requirement 😄

**Comment by DamienCassou** [comment]
@minad: your answer makes perfect sense. Thank you
@hmelman: if the classifier is disappearing, it is another reason not to split

**Comment by minad** [comment]
I don't know if the classifier will disappear since it requires a huge amount of changes to the Emacs code base (basically every completing-read call).

A small helper function could be useful to facilitate the process:

~~~ elisp
(defun complete-with-category (category collection)
  (lambda (str pred action)
    (let ((result (complete-with-action action collection str pred)))
      (if (eq action 'metadata)
        `(metadata
          (category . ,category)
          ,(cdr result))
        result))))
~~~

Which can be used as follows:

~~~ elisp
(completing-read "Prompt: "
                 (complete-with-category
                  'file
                  '("~/emacs" "/etc" "/usr")))
~~~

versus

~~~ elisp
(completing-read "Prompt: "
                  '("~/emacs" "/etc" "/usr"))
~~~

**Comment by hmelman** [comment]
> I don't know if the classifier will disappear since it requires a huge amount of changes to the Emacs code base (basically every completing-read call).

I hadn't realized it was such a large change (I'm looking at Emacs 27).  I'd think that just updating various `read-*` functions would go a long way.  There are about 60 of them, but of course you only need to deal with the ones marginalia uses.  So `read-color` and perhaps `read-face` and `read-variable` would handle those categories.  Otherwise there are just under 500 `completing-read` calls in lisp source, though I suspect you could eliminate many of them just based on the package they're in.

Of course third party packages exist too and it's great that marginalia works for them as well.  But once examples or recommendations start making it into emacs of how to properly categorize a completion set, I'd expect more to incorporate that themselves (well particularly if marginalia gets more popular).  Also, it's a kind of mechanical change that someone just starting out could pull from the emacs TODO file if it makes it in there.
