### ISSUE TITLE
In M-x, highlight commands for modes that are active

### ISSUE THREAD

**Issue by daviwil** [minad/marginalia#75]
One thing that `counsel-M-x` does which I find really helpful is to use a different face for the names of mode commands that are activated (the corresponding `-mode` variable is `t`).  For example, when `auto-save-mode` is active, the name of that command has a different foreground color in the `M-x` completion list.  I often use this as a quick way to determine whether a minor mode is turned on.  

Is there any way Marginalia could do this, or is this something that Consult should do?

**Comment by oantolin** [comment]
Marginalia cannot control what face completion candidates are displayed in, this up to the completion UI. It can only control the annotations that (some) completion UIs show alongside the candidates. So Marginalia could display a little "on" or "off" string for mode commands, or some nice unicode on and off symbols, for example. If you'd like I can help you write an enhanced command annotator that does this, but first maybe you should give `consult-minor-mode-menu` a try, since that commands let's you quickly see which minor modes are active and which ones aren't and lets you toggle them.

**Comment by minad** [comment]
> Marginalia cannot control what face completion candidates are displayed in, this up to the completion UI. It can only control the annotations that (some) completion UIs show alongside the candidates.

While this is true currently, we could add support for `affixation-functions` which are at least allowed to adjust the properties of the candidates. I also discussed with the Emacs developers if it makes sense to relax the specification of the `affixation-function` to allow transformed candidate strings. This is currently disallowed since it breaks `choose-completion`.

> ...but first maybe you should give consult-minor-mode-menu a try, since that command let's you quickly see which minor modes are active and which ones aren't and lets you toggle them.

I agree with this. Please give this command a try. I don't think I want to see the default command annotator specifically highlighting modes or adding special annotations for modes.

We already have `marginalia-annotate-minor-mode`, which is used by `consult-minor-mode-menu` and `describe-minor-mode`. This annotator is specifically tailored for this purpose. Then we support verbose variable annotations in `marginalia-annotate-variable` showing the current value.

Overall I don't toggle minor modes that often, but I am usually happy with my standard configurations. I am using tarsisus' minions to hide all the noise. I am using its mouse menu rarely, but still it is there in case I need it.

**Comment by daviwil** [comment]
Thanks!  Somehow I missed `consult-minor-mode-menu` when I was looking through the Consult commands for this, it's certainly useful!  Writing my own annotator could be useful for this honestly, I just need some way to see if the mode is on or off in the `M-x` list, another column could be totally fine for that.

I'll take a look at the source of `consult-minor-mode-menu` and see what I can learn from it.  Thanks to you both!

**Comment by minad** [comment]
> Writing my own annotator could be useful for this honestly, I just need some way to see if the mode is on or off in the M-x list, another column could be totally fine for that.

Yes, it should be pretty simple to write a modified command annotator for that. If you find other annotators which seem useful for a wide audience we can also include them here. But the current coverage seems to be already quite comprehensive.
