### ISSUE TITLE
marginalia--symbol-class documentation

### ISSUE THREAD

**Issue by iyefrat** [minad/marginalia#86]
Hey,

From checking `help--symbol-completion-table-affixation`, it seems that the `o` option in `marginalia--symbol-class` is also a marginalia addition. This should probably be documented alongside `*` and `!`. 
https://github.com/minad/marginalia/blob/4c6272ffc4836de052c8b06f681b0e700cb01602/marginalia.el#L360-L361

Have you considered upstreaming them to emacs 28? They are very useful, but I couldn't find anything to that effect.

Also, I think the explanation for the symbol classes should be added to the readme, since it's not entirely clear from a user standpoint how to figure out what they mean if you don't want to start digging through the codebase.

(sorry this isn't a PR, don't have FSF copyright assignment yet)

**Comment by minad** [comment]
> Have you considered upstreaming them to emacs 28? They are very useful, but I couldn't find anything to that effect.

It has already been discussed on emacs-devel. See also https://github.com/emacs-mirror/emacs/commit/d4ae640a3720e11fc8736a3530bba50520412023. However the upstream version only returns a single character, which is incorrect in a strict sense since Elisp is not a Lisp-1 but a Lisp-2 or rather a Lisp-n due to its many namespaces. @link0ff What about replacing `help--symbol-class` with `marginalia--symbol-class` as is? I think there is no way to compress the symbol class in a single character.

> Also, I think the explanation for the symbol classes should be added to the readme, since it's not entirely clear from a user standpoint how to figure out what they mean if you don't want to start digging through the codebase.

Of course, the documentation should be improved. See also #78. For documentation improvements one does not need the assignment btw.

**Comment by iyefrat** [comment]
> For documentation improvements one does not need the assignment btw.

Oh great, In that case I'll submit a PR. Does this cover only the readme or also code comments? I couldn't really find any explanation on it online.

**Comment by minad** [comment]
I am not sure, but afaik neither doc strings not readme is affected by the assignment.

**Comment by minad** [comment]
But I think you are in the process of getting the assignment because of embark? So we can just wait here
