### ISSUE TITLE
Add colour to variable annotations?

### ISSUE THREAD

**Issue by tecosaur** [minad/marginalia#89]
Heyo,

I've just started using this thanks to the `vertico` Doom module being merged a few hours ago :tada:.

In shifting over from Ivy there are a few things I'm missing though, one of which is the coloured variables based on type.
I notice that marginalia goes to the effort of finding out some information about the variables, but then displays them all with the same face. Have you considered finding out a little bit more (type information) and then picking a sensible face based on that?

I find this quite useful for spotting what I want.

![image](https://user-images.githubusercontent.com/20903656/126912116-3e738bb8-73e2-48e1-a103-6202dce92dac.png)

If this is of interest, I'd be happy to spin up a PR.

**Comment by minad** [comment]
Hey, great to hear that you are trying out these packages!

> In shifting over from Ivy there are a few things I'm missing though, one of which is the coloured variables based on type.
I notice that marginalia goes to the effort of finding out some information about the variables, but then displays them all with the same face. Have you considered finding out a little bit more (type information) and then picking a sensible face based on that?

You mean changing the color of the candidate itself? There are two reasons why this feature is not implemented:

1. The `annotation-function` of pre-Emacs 28 and the `affixation-function` of Emacs 28 do not support modification of the candidate. Or it is at least undefined if it is allowed. I want to change this upstream in Emacs to explicitly allow modifications. I find time for a patch and to go through the involved emacs-devel discussions. It is a bit of a rabbit hole, the Emacs 28 `affixation-function` should better be replaced by a more general `decoration-function`. But this is the reason why Marginalia currently does not make an attempt to modify candidate strings.

2. Elisp is a Lisp-n with n different namespaces (variables, functions, faces, groups, ...). This means picking a face is nonsensical in a strict sense. The indicator behind the candidate (c@v, clv*) reflects this. However one may still make a pragmatic choice, by checking first for commands and then variables in order to pick a face (Embark does the same with its action keymaps). 

> If this is of interest, I'd be happy to spin up a PR.

You can give it a try if you are interested. Currently the Marginalia annotation functions are quite simple, they only return a string. So in order to also modify the candidate itself one would also have to return the modified candidate string. Another quick and dirty option would be to mutate the candidate string itself, but this is probably not a good idea since the completion UI may rely on the candidate being not modified. So this all needs a bit of thought and I am not sure if it is worth working on this as long as the situation in Emacs  regarding the `affixation-function` (and a possible `decoration-function`) itself is unclear. As a first step you can implement your own `affixation-function` as in @iyefrat's all-the-icons-completion package. Of course you can also hack Vertico itself, see `vertico--format-candidate` and the vertico-extensions packages, some of them modify the formatting.

**Comment by oantolin** [comment]
@minad I think @tecosaur meant changing the color of the variable _value_ depending on its type, as seen in the screenshot. Strings are green, symbols are yellow, numbers are white, etc.

**Comment by minad** [comment]
Oh okay, then of course I want a PR for this. This is a good idea!

**Comment by minad** [comment]
@tecosaur I didn't look close enough at your screenshot. It seems you already have the patch in the pipeline then? :grin:

**Comment by tecosaur** [comment]
I have indeed :slightly_smiling_face: I'll make a PR shortly.

By the way minad I'm investigating some other visual improvements and a performance issue when scrolling through candidates with vertico/marginalia with iyefrat on the Doom discord. If you happen to have a discord account, please feel free to join us :smiley:.

**Comment by tecosaur** [comment]
This has now been done.
